export const partnerQuestionsPost = {
  "slug": "questions-to-ask-your-partner",
  "title": "150 Questions to Ask Your Partner to Feel Closer",
  "seoTitle": "150 Questions to Ask Your Partner to Feel Closer",
  "description": "150 questions to ask your partner, from funny conversation starters to romantic, thoughtful, and long-distance prompts. Pick a few and take turns.",
  "excerpt": "Go beyond “how was your day?” with playful, romantic, and thoughtful questions that leave room for a real conversation.",
  "image": "/blog/questions-to-ask-your-partner.png",
  "imageAlt": "Hand-drawn couple sharing conversation cards on a lilac sofa beneath the title 150 Questions to Ask Your Partner to Feel Closer",
  "date": "2026-09-12",
  "updatedDate": "2026-09-12",
  "displayDate": "September 12, 2026",
  "author": "The Lovla Team",
  "readingMinutes": 16
};

export const partnerQuestionGroups = [
  {
    "title": "Easy questions for an ordinary evening",
    "id": "easy",
    "intro": "Start with something small. An answer about lunch can lead somewhere interesting if you give it a little room.",
    "start": 1,
    "questions": [
      "What was the nicest unexpected part of your day?",
      "What has been taking up more of your attention than you expected?",
      "What small thing would make tomorrow easier?",
      "What have you been looking forward to this week?",
      "What made you laugh recently that I missed?",
      "What is something you enjoyed today without taking a picture of it?",
      "What meal would match your mood tonight?",
      "What would you like a little more time for this weekend?",
      "What song feels like your week so far?",
      "What ordinary errand would be more fun if we did it together?",
      "What have you changed your mind about lately?",
      "What is something you noticed on your usual route today?",
      "What part of your routine feels especially good right now?",
      "What would you tell me about today if we only had five minutes?",
      "What would make this evening feel well spent?"
    ]
  },
  {
    "title": "Funny questions that invite a story",
    "id": "funny",
    "intro": "Leave room for ridiculous answers. You do not need to turn every joke into a serious discussion.",
    "start": 16,
    "questions": [
      "What harmless thing would you become an outrageously strict judge of?",
      "What would our relationship's customer-service department get the most calls about?",
      "What would your least useful superpower be?",
      "What everyday task deserves a dramatic movie soundtrack?",
      "What would you put in a museum about your teenage self?",
      "What would we accidentally become famous for on a road trip?",
      "What food opinion would you defend in a completely unnecessary debate?",
      "What would your pet say about your daily habits?",
      "What is the most absurd thing you believed as a child?",
      "What would you name a restaurant that served only your midnight snacks?",
      "What is your most memorable attempt to look cooler than you felt?",
      "What household item would you give an employee-of-the-month award?",
      "What would happen if we swapped wardrobes for a week?",
      "What minor inconvenience would be the villain in your autobiography?",
      "What silly competition should we invent for our next date?"
    ]
  },
  {
    "title": "Questions about childhood and the people who shaped you",
    "id": "childhood",
    "intro": "Choose the memories you want to share. A childhood conversation can stay with favorite places and funny stories; nobody owes a difficult history.",
    "start": 31,
    "questions": [
      "What place from childhood can you still picture in detail?",
      "What did a good day after school look like for you?",
      "Who made you feel understood when you were young?",
      "What family saying do you still catch yourself using?",
      "What did you collect or keep in a secret little stash?",
      "What did you love doing before you worried about being good at it?",
      "What childhood celebration would you like to experience again?",
      "What was a small act of kindness from an adult that stayed with you?",
      "What did you think being grown up would feel like?",
      "What story does your family tell about you that needs your version added?",
      "What did you learn from your first close friendship?",
      "What part of where you grew up do you wish I could see through your eyes?",
      "What rule from your childhood would you keep in your own home?",
      "What did your younger self care about that still matters to you?",
      "What would you like me to understand about the person you were before we met?"
    ]
  },
  {
    "title": "Questions about your memories together",
    "id": "memories",
    "intro": "You may remember the same day differently. Compare the details with curiosity, without deciding which version wins.",
    "start": 46,
    "questions": [
      "What small detail from our first conversations do you remember?",
      "What moment made being around me feel easier?",
      "What ordinary day together would you happily revisit?",
      "What did you think about on your way home from an early date?",
      "What surprise about me turned out to be a good one?",
      "What is a time we laughed when everything was going wrong?",
      "What place feels connected to us even though nobody else would know it?",
      "What photo of us has a story the picture does not show?",
      "What is something we used to do that you miss?",
      "What moment together felt like a new chapter?",
      "What trip taught you something unexpected about us?",
      "What is a kindness from me that I might have forgotten?",
      "What part of our early relationship would you tell a friend about first?",
      "What shared memory would you turn into a short film?",
      "What would you like us to remember about this season of our lives?"
    ]
  },
  {
    "title": "Romantic questions about affection and closeness",
    "id": "romantic",
    "intro": "Be specific about moments and gestures. You can appreciate what already works while mentioning something you would enjoy more of.",
    "start": 61,
    "questions": [
      "What small gesture from me makes you feel wanted?",
      "What kind of greeting feels best after we have been apart?",
      "What is your favorite way for us to be affectionate in an ordinary moment?",
      "What compliment from me has stayed with you?",
      "What makes a date feel romantic to you beyond where we go?",
      "What is something about our connection you appreciate more with time?",
      "What kind of surprise feels thoughtful rather than stressful?",
      "What helps you relax into time alone together?",
      "What is a way you like being cared for that you rarely ask for?",
      "What does a really good slow morning together look like?",
      "What is something you find attractive about me that has nothing to do with appearance?",
      "What would you enjoy hearing from me more often?",
      "What is one way we could make our goodbyes feel warmer?",
      "What kind of affection feels comforting when you are tired?",
      "What little tradition would make an ordinary day feel like ours?"
    ]
  },
  {
    "title": "Questions about support and feeling understood",
    "id": "support",
    "intro": "Ask these when you have the attention to listen. Let your partner describe what helps before offering solutions.",
    "start": 76,
    "questions": [
      "What is something you wish people understood about your current workload?",
      "What helps you feel listened to when you are venting?",
      "What does useful support look like when you cannot change a situation yet?",
      "What signs tell you that you need a break?",
      "What is an effort you have been making that might be hard for others to see?",
      "What helps you come down from a stressful day?",
      "What would you like me to ask before I offer advice?",
      "What kind of encouragement feels believable to you?",
      "What makes asking for help easier?",
      "What is something you would like to celebrate even though it seems small?",
      "What do you need more room to figure out at your own pace?",
      "What is a way I could make a busy week lighter for you?",
      "What helps you feel connected when you do not have much energy to talk?",
      "What have you learned about taking care of yourself recently?",
      "What would feeling supported this month look like in practice?"
    ]
  },
  {
    "title": "Questions about your everyday life as a team",
    "id": "everyday",
    "intro": "Talk about the life you actually have, including different homes or schedules. Look for one manageable change instead of redesigning everything tonight.",
    "start": 91,
    "questions": [
      "What recurring task takes more energy than it appears to?",
      "What part of our schedules works well together?",
      "What is one decision we could make once instead of revisiting every week?",
      "What does enough alone time look like for you lately?",
      "What shared space or routine would you like to make more comfortable?",
      "What makes a plan feel flexible enough for you to enjoy it?",
      "What is a small responsibility you would appreciate help with?",
      "What do we do well when we have to solve a practical problem?",
      "What is your ideal balance between going out and staying in right now?",
      "What is a spending priority you would like me to understand better?",
      "What habit helps you feel settled at home?",
      "What is one thing we could stop doing out of obligation?",
      "What would make planning our time together simpler?",
      "What do you want us to protect time for, even in a busy week?",
      "What small improvement could we try for a week and then reconsider?"
    ]
  },
  {
    "title": "Questions about dreams, values, and the future",
    "id": "future",
    "intro": "An answer can be an idea, not a commitment. Ask what appeals to your partner before moving into budgets, dates, or logistics.",
    "start": 106,
    "questions": [
      "What would you try if being a beginner did not feel embarrassing?",
      "What kind of ordinary day would you like more of in five years?",
      "What is a dream you have not talked about much yet?",
      "What does a meaningful version of success look like to you now?",
      "What would you like to learn just for the pleasure of learning it?",
      "What place would you like to live in briefly, and what draws you there?",
      "What do you hope stays the same as our lives change?",
      "What value would you want a big decision of ours to reflect?",
      "What would you like to give more of your time or energy to?",
      "What is a future experience you would enjoy preparing for together?",
      "What part of your life do you want to feel less rushed?",
      "What does belonging somewhere mean to you?",
      "What is a goal you have outgrown but still feel expected to pursue?",
      "What would you like our home, shared or separate, to make room for?",
      "What small step toward something you want would feel possible this month?"
    ]
  },
  {
    "title": "Questions for when you are apart",
    "id": "apart",
    "intro": "These work over a call, a voice note, or a few messages. Share what would feel good without treating a response time as a measure of affection.",
    "start": 121,
    "questions": [
      "What part of your day is hardest for me to picture from here?",
      "What would you show me first if I could visit for an hour today?",
      "What kind of message makes you smile when you are busy?",
      "What helps a call feel like time together rather than a daily report?",
      "What is one routine we could share from different places?",
      "What do you want our first hour of the next visit to feel like?",
      "What is something about your current surroundings you wish I knew?",
      "What makes saying goodnight from a distance feel better?",
      "What is a way to include each other in our days without being on our phones constantly?",
      "What would you like us to try on our next video call?",
      "What do you appreciate about how we handle being apart?",
      "What makes a surprise delivery or letter feel personal to you?",
      "What would help when our energy levels or schedules do not line up?",
      "What is one detail of your life there you would like me to ask about more?",
      "What are you most looking forward to doing together that costs little or nothing?"
    ]
  },
  {
    "title": "Deeper questions to take your time with",
    "id": "deeper",
    "intro": "Pick these when you both feel willing to linger. Passing is allowed, and one thoughtful answer can be plenty for a night.",
    "start": 136,
    "questions": [
      "What part of yourself have you come to understand better in the past year?",
      "What belief about love has changed as you have grown?",
      "What makes you feel accepted without having to perform?",
      "What is something you are learning to be kinder to yourself about?",
      "What experience changed the way you define strength?",
      "What do you find difficult to put into words even with people you trust?",
      "What does being able to depend on someone mean to you?",
      "What would you like to feel less pressure to prove?",
      "What is a part of your identity you want more space to explore?",
      "What does a sincere apology need to include for you?",
      "What helps you return to a conversation after you have needed space?",
      "What is something you hope I stay curious about as we get older?",
      "What do you want to be remembered for by the people closest to you?",
      "What have you learned about yourself through being with me?",
      "What is one thing you would like us to carry from this conversation into tomorrow?"
    ]
  }
] as const;
